imgur refactor

diff --git a/bin/imgur b/bin/imgur
--- a/bin/imgur
+++ b/bin/imgur
@@ -13,7 +13,7 @@
 # \__,_// .___//_/ \____/ \__,_/ \__,_/(_)   
 #      /_/   https://github.com/guyhughes    
 #            ported to sh from bash ^,^
-# 
+###1 Meta
 # Original Author: Bart Nagel <bart@tremby.net>, version 4
 #
 # Required: curl
@@ -21,14 +21,7 @@
 # Optional: xsel or xclip for automatically putting the URLs on the X selection 
 # for easy pasting
 #
-# Instructions:
-# Put it somewhere in your path and maybe rename it:
-# 	mv ~/Downloads/imgurbash.sh ~/bin/imgur
-# Make it executable:
-# 	chmod +x ~/bin/imgur
-# Optional, since Alan kindly provided an API key for this script: stick your 
-# API key in the top:
-# 	vim ~/bin/imgur
+###1 Instructions
 # Upload an image:
 # 	imgur images/hilarious/manfallingover.jpg
 # Upload multiple images:
@@ -37,7 +30,7 @@
 # stderr). If you have xsel or xclip the URLs will also be put on the X 
 # selection, which you can usually paste with a middle click.
 
-# API Key provided by Alan@imgur.com
+###1 constants
 apikey="b3625162d3418ac51a9ee805b1840452"
 
 usage () {
@@ -48,13 +41,17 @@ usage () {
 	echo "easy pasting." >&2
 }
 
-# check API key has been entered
+###1 sanity preflight
 if [ "$apikey" = "Your API key" ]; then
 	echo "You first need to edit the script and put your API key in the variable near the top." >&2
 	exit 15
 fi
+if ! type curl >/dev/null 2>/dev/null; then
+	echo "Couln't find curl, which is required." >&2 
+	exit 17
+fi
 
-# parse args
+###1 parse opts
 if [ "$1" = "-h" || "$1" = "--help" ]; then
 	usage
 	exit 0
@@ -64,14 +61,10 @@ elif [ $# = 0 ]; then
 	exit 16
 fi
 
-if ! type curl >/dev/null 2>/dev/null; then
-	echo "Couln't find curl, which is required." >&2 
-	exit 17
-fi
-
 clip=""
 errors=false
 
+###1 parse args
 while [ $# -gt 0 ]; do
 	file="$1"
 	shift
@@ -98,29 +91,28 @@ while [ $# -gt 0 ]; do
 		continue
 	fi
 
-	# parse the response and output our stuff
 	url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
 	deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
 	echo $url
 	echo "Delete page: $deleteurl" >&2
 
-	# append the URL to a string so we can put them all on the clipboard later
-	clip="$clip$url
-"
+	clip="$clip$url"
 done
 
-# put the URLs on the clipboard if we have xsel or xclip
+###1 copy to clipboard
 if [ $DISPLAY ]; then
 	if !! type xsel >/dev/null 2>/dev/null; then
      printf $clip | xsel
    elif !! type xclip >/dev/null 2>/dev/null; then;
      printf $clip | xclip
    else
-     echo "Haven't copied to the clipboard: no xsel or xclip" >&2
+     echo "Couldn't copy: no xsel or xclip" >&2
 else
-	echo "Haven't copied to the clipboard: no \$DISPLAY" >&2
+	echo "Couldn't copy: no \$DISPLAY" >&2
 fi
 
+###1 error exit code
 if $errors; then
 	exit 1
 fi
+# vim: set ft=sh tw=0 ts=2 sw=2 sts=2 fdm=marker fmr=###,### et:
